name: Sync
 
on:
  push:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
      name: "checkout"
    - name: decK ping
      id: decK_ping
      uses: ./
      with:
        command: "ping"
        options: "--kong-addr http://172.28.12.124:8001"
    - name: decK validate
      id: decK_validate
      uses: ./
      with:
        command: "validate"
        options: "--kong-addr http://172.28.12.124:8001" 
        kong_workspaces: "kong"
    - name: decK sync
      id: decK_sync
      uses: ./
      with:
        command: "sync"
        options: "--kong-addr http://172.28.12.124:8001" 
        kong_workspaces: "kong"
