name: Validate and Import OpenAPI on Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        npm install -g @kong/insomnia-inso@latest
        npm install -g @kong/deck@latest

    - name: Validate OpenAPI
      run: |
        inso lint spec "Nyltech-OpenAPI.yaml"
      continue-on-error: true

    - name: Import to Kong
      run: |
        deck ping ./openapi-spec.yaml --kong-addr http://172.28.12.124:8001
