name: Sync
 
on:
  push:
    branches: [ main ]
 
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./openapi-declarative.sh
         ./openapi-declarative.sh
      shell: bash
