name: Kong Deck on Code Push

on:
  push:
    branches:
      - main

jobs:
  kong-deck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Kong Deck CLI
      uses: Kong/deck@v2
      with:
        version: "2.5.0"
        
    - name: Authenticate with Kong
      run: kong config init http://172.28.12.124:8001"

    - name: Sync Kong configuration
      run: kong deck sync
