name: Validate and Import OpenAPI on Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Deck
      uses: kong/setup-deck@v1
      with: 
        deck-version: 1.8.0

    - name: Run Deck
      run: deck ping --kong-addr http://172.28.12.124:8001
